AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  helloworld:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.render
      Runtime: nodejs8.10
      CodeUri: lambda-app
      Description: Starter AWS Lambda function with dev-toolkit.
      MemorySize: 256
      Timeout: 20
      Events:
        HelloWorldSamAPI:
          Type: Api
          Properties:
            Path: /render-test
            Method: GET
