AWSTemplateFormatVersion: "2010-09-09"
Description: A starter AWS Lambda function.
Resources:
  helloworldRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: AllowXRayPermission
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - xray:*
                Resource:
                  - !Sub "*"
  ServerlessRestApiDeploymentc3f217c6f1:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ServerlessRestApi
      Description: "RestApi deployment id: c3f217c6f10e6a04629e51820856b520a84a99e9"
      StageName: Stage
  helloworldHelloWorldSamAPIPermissionTest:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Ref: helloworld
      SourceArn:
        Fn::Sub:
          - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/render-test
          - __Stage__: "*"
            __ApiId__:
              Ref: ServerlessRestApi
  ServerlessRestApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      DeploymentId:
        Ref: ServerlessRestApiDeploymentc3f217c6f1
      RestApiId:
        Ref: ServerlessRestApi
      StageName: Prod
      MethodSettings:
        - ResourcePath: /render-test
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300

  helloworldHelloWorldSamAPIPermissionProd:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Ref: helloworld
      SourceArn:
        Fn::Sub:
          - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/render-test
          - __Stage__: Prod
            __ApiId__:
              Ref: ServerlessRestApi
  helloworld:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambda-app
      Description: Starter AWS Lambda function with dev-toolkit.
      Tags:
        - Value: SAM
          Key: lambda:createdBy
      MemorySize: 256
      Handler: handler.render
      Role:
        Fn::GetAtt:
          - helloworldRole
          - Arn
      Timeout: 40
      Runtime: nodejs8.10
      TracingConfig:
        Mode: Active
  ServerlessRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      MinimumCompressionSize: 0
      Body:
        info:
          version: "1.0"
          title:
            Ref: AWS::StackName
        paths:
          "/render-test":
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${helloworld.Arn}/invocations
              responses: {}
        swagger: "2.0"
